services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET = BUCKET_NAME          # The name of your bucket
      - DOCKER_INFLUXDB_INIT_ORG = ORG_NAME              # The name of your organization
      - DOCKER_INFLUXDB_INIT_USERNAME= my-user 
      - DOCKER_INFLUXDB_INIT_PASSWORD= my-password 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN = 3mH2JVxF3-eyZA_giUzWRj0oz0CcGhhgn7mCjiuW5TiIO31E0x-PGufYp9MyTcSzALEDiDgJbjjLaspGJcU-Aw== # Admin token
      - DOCKER_INFLUXDB_INIT_USER_TOKEN = 3mH2JVxF3-eyZA_giUzWRj0oz0CcGhhgn7mCjiuW5TiIO31E0x-PGufYp9MyTcSzALEDiDgJbjjLaspGJcU-Aw==  # Non-admin user token  
    ports:
      - "8086:8086"  # InfluxDB HTTP API port


  server-mock-container :
    image: server-mock-image
    container_name: server-mock-container
